### ISSUE TITLE
[iPTF16fnl] Negative magnitude errors

### ISSUE THREAD

**Issue by hombit** [astrocatalogs/tidaldisruptions#3]
`iPTF16fnl` photometry has a lot of negative `e_magnitude` values. Example:

```json
{
	"time":"57681.3",
	"band":"g",
	"e_magnitude":"-0.50",
	"instrument":"CFH12k",
	"magnitude":"19.56",
	"telescope":"P48",
	"u_time":"MJD",
	"source":"1"
},
```

**Comment by guillochon** [comment]
It appears that the LaTeX table that this data was pulled from used a negative value on the error as a placeholder for instances where the error was not defined; the published version shows no `e_magnitude` reported for those same measurements. So you can safely ignore `e_magnitude` for those observations.

The import has been fixed in https://github.com/astrocatalogs/tidaldisruptions/commit/48f4ec29b0d81b4703424620a0c7c3ba01109145 and will live on tde.space by tomorrow evening.
